FROM python:3.12.2-slim

WORKDIR /app

#ADD ./ta-lib-deps/ta-lib-0.6.3-src.tar.gz .
#COPY ./python-deps/requirements.txt .
#
#RUN apt -y update && \
#    apt -y install gcc && \
#    apt -y install make && \
#    cd ta-lib-0.6.3 && \
#    ./configure --prefix=/usr && \
#    make && \
#    make install && \
#    pip install -r /app/requirements.txt

ENTRYPOINT ["python"]
